review_result_labels:
    - label: WRONG_FORMAT
      label_ru: 'Неверный формат'
      public_comment: 'Заявка не соответствует формату подачи документов.'
    - label: CANT_SEE_URL_ADRESS
      label_ru: 'Адрес сайта невиден'
      public_comment: 'Не удалось рассмотреть адрес сайта на видеозаписи'
    - label: BAD_PHOTO
      label_ru: 'Плохое качество фото'
      public_comment: 'Фотографии плохого качества'
    - label: BAD_DOCUMENTS
      label_ru: 'Часть документа скрыта'
      public_comment: 'Часть документа скрыта'
    - label: SOMEONE_ELSE_DOCUMENT
      label_ru: 'Документы закреплены за другой записью'
      public_comment: 'Документы уже закреплены за другой учетной записью'
    - label: BAD_DOCUMENTS_WITH_FACE
      label_ru: 'Фото документа на фоне лица плохого качества'
      public_comment: 'Фото паспорта на фоне лица плохого качества'
    - label: BAD_DOCUMENT_ON_VIDEO
      label_ru: 'Данные паспорта на видеозаписи не читаемы'
      public_comment: 'Данные паспорта на видеозаписи не читаемы'
    - label: VIDEO_IS_MISSING
      label_ru:  'Отсутствует видеозапись'
      public_comment: 'В заявке отсутствует видеозапись'
    - label: BAD_DOCUMENTS_WITH_SITE
      label_ru:  'Фото паспорта на фоне сайта плохого качества'
      public_comment: 'Фото паспорта на фоне сайта плохого качества'
    - label: NO_DOCUMENTS_WITH_FACE
      label_ru: 'Отсутствует фотография документа на фоне лица'
      public_comment: 'Отсутствует фотография документа на фоне лица'
    - label: NO_DOCUMENTS_WITH_SITE
      label_ru: 'Отсутствует фотография документа на фоне сайта'
      public_comment: 'Отсутствует фотография документа на фоне сайта'
    - label: BAD_CONTROL_TEXT
      label_ru: 'Некорректно произнесен контрольный текс.'
      public_comment: 'Некорректно произнесен контрольный текст'
    - label: BAD_DOCUMENT_ID
      label_ru: 'ID документа не соответствует указанному в заявке, или отсутствует на фото'
      public_comment: 'ID документа не соответствует указанному в заявке, или отсутствует на фото'
    - label: BAD_VIDEO
      label_ru: 'Битый файл видеозаписи'
      public_comment: 'Битый файл видеозаписи'
    - label: BLUR_DOCUMENTS
      label_ru: 'Размыт текст документа'
      public_comment: 'Размыт текст документа'
    - label: EXPOSED_DOCUMENTS
      label_ru: 'Засвечен текст документа'
      public_comment: 'Засвечен текст документа'

